### ISSUE TITLE
epubcheck1_recursive_checker1: Run on Windows

### ISSUE THREAD

**Issue by jschvartz** [publishing-systems/automated_digital_publishing#2]
Hi Stephan,

I wanted to try your gui (WIN 7).
Builds all right, but i have a problem when trying to execute (see below).
Epubcheck.jar is working ok and I placed it in 'worflows' directory as well as in the upper directory ...
Maybe java or windows does not like the mixed notation '..workflow/..\epubcheck.jar'  ???

Any idea ?
Thanks,
Joel

> java epubcheck1_recursive_checker1  jobfile.xml ../out
epubcheck1_recursive_checker1 workflow Copyright (C) 2015 Stephan Kreutzer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. See the GNU Affero General Public
License 3 or any later version for details. Also, see the source code
repository https://github.com/publishing-systems/automated_digital_publishing/
or the project website http://www.publishing-systems.org.

Error: Unable to access jarfile /T:/EpubCheck/automated_digital_publishing-master/epubcheck/epubcheck1/workflows/..\epubcheck.jar

**Comment by skreutzer** [comment]
The latest commit #125 should have fixed this. The problem isn't so much the slash/backslash in "workflows/..\epubcheck", but the leading slash before the drive letter 'T', which leads to an invalid path under Microsoft Windows. In absence of Microsoft Windows on my part, I just didn't run into this problem earlier, but I'll try to verify if the latest commit solves this issue or not. Thank you very much for reporting it!

**Comment by jschvartz** [comment]
works nice now on windows.
May i suggest:
- display epubcheck version
- make it work with hotfolders, instead of having to hit the 'check' button.
So it could be running, just placing an epub in the folder would start the check.
(maybe with a progression bar ?)

Thanks anyway, already usefull as is.

Joel

**Comment by skreutzer** [comment]
Now spaces in the installation path should work, too.
